spring:
  profiles:
    active: local
  jpa:
    generate-ddl: false
#    show-sql: true

  hibernate:
    use-new-id-generator-mappings: false

  database-platform: org.hibernate.dialect.PostgreSQLDialect
